// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: interpreter/proto/diary.proto

package interpreterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diary         string                 `protobuf:"bytes,1,opt,name=diary,proto3" json:"diary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryRequest) Reset() {
	*x = DiaryRequest{}
	mi := &file_interpreter_proto_diary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryRequest) ProtoMessage() {}

func (x *DiaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_diary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryRequest.ProtoReflect.Descriptor instead.
func (*DiaryRequest) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_diary_proto_rawDescGZIP(), []int{0}
}

func (x *DiaryRequest) GetDiary() string {
	if x != nil {
		return x.Diary
	}
	return ""
}

type DiaryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        string                 `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiaryReply) Reset() {
	*x = DiaryReply{}
	mi := &file_interpreter_proto_diary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiaryReply) ProtoMessage() {}

func (x *DiaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_interpreter_proto_diary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiaryReply.ProtoReflect.Descriptor instead.
func (*DiaryReply) Descriptor() ([]byte, []int) {
	return file_interpreter_proto_diary_proto_rawDescGZIP(), []int{1}
}

func (x *DiaryReply) GetTokens() string {
	if x != nil {
		return x.Tokens
	}
	return ""
}

var File_interpreter_proto_diary_proto protoreflect.FileDescriptor

const file_interpreter_proto_diary_proto_rawDesc = "" +
	"\n" +
	"\x1dinterpreter/proto/diary.proto\x12\vinterpreter\"$\n" +
	"\fDiaryRequest\x12\x14\n" +
	"\x05diary\x18\x01 \x01(\tR\x05diary\"$\n" +
	"\n" +
	"DiaryReply\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\tR\x06tokens2V\n" +
	"\x11InterpreterServer\x12A\n" +
	"\tInterpret\x12\x19.interpreter.DiaryRequest\x1a\x17.interpreter.DiaryReply\"\x00B,Z*food-interpreter/interpreter/interpreterpbb\x06proto3"

var (
	file_interpreter_proto_diary_proto_rawDescOnce sync.Once
	file_interpreter_proto_diary_proto_rawDescData []byte
)

func file_interpreter_proto_diary_proto_rawDescGZIP() []byte {
	file_interpreter_proto_diary_proto_rawDescOnce.Do(func() {
		file_interpreter_proto_diary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interpreter_proto_diary_proto_rawDesc), len(file_interpreter_proto_diary_proto_rawDesc)))
	})
	return file_interpreter_proto_diary_proto_rawDescData
}

var file_interpreter_proto_diary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interpreter_proto_diary_proto_goTypes = []any{
	(*DiaryRequest)(nil), // 0: interpreter.DiaryRequest
	(*DiaryReply)(nil),   // 1: interpreter.DiaryReply
}
var file_interpreter_proto_diary_proto_depIdxs = []int32{
	0, // 0: interpreter.InterpreterServer.Interpret:input_type -> interpreter.DiaryRequest
	1, // 1: interpreter.InterpreterServer.Interpret:output_type -> interpreter.DiaryReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interpreter_proto_diary_proto_init() }
func file_interpreter_proto_diary_proto_init() {
	if File_interpreter_proto_diary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interpreter_proto_diary_proto_rawDesc), len(file_interpreter_proto_diary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interpreter_proto_diary_proto_goTypes,
		DependencyIndexes: file_interpreter_proto_diary_proto_depIdxs,
		MessageInfos:      file_interpreter_proto_diary_proto_msgTypes,
	}.Build()
	File_interpreter_proto_diary_proto = out.File
	file_interpreter_proto_diary_proto_goTypes = nil
	file_interpreter_proto_diary_proto_depIdxs = nil
}
