// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: interpreter/proto/diary.proto

package interpreterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterpreterServer_Interpret_FullMethodName = "/interpreter.InterpreterServer/Interpret"
)

// InterpreterServerClient is the client API for InterpreterServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterpreterServerClient interface {
	Interpret(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*DiaryReply, error)
}

type interpreterServerClient struct {
	cc grpc.ClientConnInterface
}

func NewInterpreterServerClient(cc grpc.ClientConnInterface) InterpreterServerClient {
	return &interpreterServerClient{cc}
}

func (c *interpreterServerClient) Interpret(ctx context.Context, in *DiaryRequest, opts ...grpc.CallOption) (*DiaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiaryReply)
	err := c.cc.Invoke(ctx, InterpreterServer_Interpret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterpreterServerServer is the server API for InterpreterServer service.
// All implementations must embed UnimplementedInterpreterServerServer
// for forward compatibility.
type InterpreterServerServer interface {
	Interpret(context.Context, *DiaryRequest) (*DiaryReply, error)
	mustEmbedUnimplementedInterpreterServerServer()
}

// UnimplementedInterpreterServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterpreterServerServer struct{}

func (UnimplementedInterpreterServerServer) Interpret(context.Context, *DiaryRequest) (*DiaryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Interpret not implemented")
}
func (UnimplementedInterpreterServerServer) mustEmbedUnimplementedInterpreterServerServer() {}
func (UnimplementedInterpreterServerServer) testEmbeddedByValue()                           {}

// UnsafeInterpreterServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterpreterServerServer will
// result in compilation errors.
type UnsafeInterpreterServerServer interface {
	mustEmbedUnimplementedInterpreterServerServer()
}

func RegisterInterpreterServerServer(s grpc.ServiceRegistrar, srv InterpreterServerServer) {
	// If the following call pancis, it indicates UnimplementedInterpreterServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterpreterServer_ServiceDesc, srv)
}

func _InterpreterServer_Interpret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterpreterServerServer).Interpret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterpreterServer_Interpret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterpreterServerServer).Interpret(ctx, req.(*DiaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterpreterServer_ServiceDesc is the grpc.ServiceDesc for InterpreterServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterpreterServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interpreter.InterpreterServer",
	HandlerType: (*InterpreterServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Interpret",
			Handler:    _InterpreterServer_Interpret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interpreter/proto/diary.proto",
}
