name: 'Run Lexer Tests'
run-name: 'Run Lexer Tests'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.23.0'
      - name: Run Lexer tests
        run: cd lexer && go test -v
