name: 'Run Lexer Tests'
run-name: 'Run Lexer Tests'
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.23.0'
          cache-dependency-path: "**/*.sum" # TODO, new error, "Restore cache failed: Some specified paths were not resolved, unable to cache dependencies."
          cache: true
      - name: Run Lexer tests
        run: cd lexer && go test -v
  release:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
