# TODO look into requiring the other two workflows to pass.
name: 'Push Docker Image'
run-name: 'Push Docker Image'
on:
  workflow_run:
    workflows: [Run Lexer Tests] # TODO this will cause a race condition of the Infra deploy hasn't created the GAR repo yet.
    types:
      - completed
jobs:
  push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/${{ vars.GCP_WIF_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
      - name: Get Short GitHub SHA
        run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Docker Image
        run: 'docker build -t food-interpreter:${{ env.SHA_SHORT }} .'
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/food-interpreter-repository/food-interpreter:latest
  echo-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Lexer Tests failed. Pushing docker image to GAR cancelled."
